# Generated by Django 3.2 on 2024-11-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpay_app', '0003_paymentreminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentReminder',
        ),
    ]
